services:
  db-reservas:
    image: mysql:latest
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: s83n38DGB8d72
    ports:
      - 3307:3306  # <--- Mapea el puerto 3306 interno al 3307 externo
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer:latest
    restart: "no"
    ports:
      - 8181:8080