services:
  db-reservas:
    image: mysql:latest
    # command: --mysql-native-password=ON
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: s83n38DGB8d72
    ports:
      - 3307:3306
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer:latest
    restart: "no"
    ports:
      - 8181:8080
